### PR TITLE
984 - Add auth0 and guardian pipeline (do not merge)

### PR DESCRIPTION
**Pull request by ijadams**
### Description: Adding Auth0

*** This PR is more for documenting a potential auth0 implementation ***

### Background -
https://revelrylabs.slack.com/archives/C045BEDQS/p1620926359490100

### CODE REVIEW

**Comment by grossvogel** [comment]
My feeling on this is that we should keep it as a reference for _how_ to integrate these things but not merge it into the template because it's not necessarily going to be the right solution for all / most apps.

**Comment by ijadams** [comment]
@grossvogel Love that idea. Do you have any recommendations on how to document it? It sounded like we should probably have an engineering meeting or something to discuss how we want to execute making this starter less opinionated and more documented in terms of potential implementations of different tools.

**Comment by grossvogel** [comment]
@ijadams I can think of some ways to document it, but I don't love any of them. We could write a wiki page, add something to the `study-hall` repo, or the `playbook` repo, or even put it in the README of the app template itself (though that gets copied into every generated app so that's probably a bad one.)

The last time we had something like this (with a totally different auth scheme in fact), it had a kinda natural home [here](https://github.com/revelrylabs/react-native-template-revelry/blob/master/GETTING_STARTED.md#with-revelry_phoenix_app_template) (see mention of #540)

**Comment by ijadams** [comment]
Archiving

**Pull request closed without merging**
