### PR TITLE
updated config to runtime model

### PR DESCRIPTION
**Pull request by pjdiiori**
connects to #929 

#### Description: Changed "releases.exs" to "runtime.exs"

Also put configurations within a `if config_env() == :prod do` block.

#### Reviewer don't-forgets:

- [x] Test coverage feels appropriate, given potential risk
- [x] We're not doubling down on already-bad code
- [x] If there are web UI changes, they don't add anything that could be considered client-side page navigation (unless pre-approved as being necessary by another engineer)
- [x] If there are web UI changes, they don't add any AJAX form submits (unless pre-approved as being necessary by another engineer)
- [x] If there are any lint rules disabled, they are disabled per-line, and were (in the reviewer's judgment) appropriate to disable
- [x] Any new environment variables used in the app are both documented and have been added to both staging and production environments already
- [x] Potential race conditions are either inconsequential, or the code prevents them from occurring.
- [x] If this is a UI change that called for screenshots/GIFs, in the reviewer's judgement, they were included

### CODE REVIEW

**Review by grossvogel — APPROVED** [review]
Looks like the right thing to me, thanks for doing this!!!

(Next I want to remove instances of `System.get_env()` from the _other_ config files where they're just misleading 😈 )

**Comment by pjdiiori** [comment]
> (Next I want to remove instances of System.get_env() from the other config files where they're just misleading 😈 )

@grossvogel  Could you elaborate on this or maybe even pair with me on it to explain if you have time?

**Comment by grossvogel** [comment]
@pjdiiori yeah, Elixir has a profusion of config files:
- `config.exs` applies generally for every environment (**compile-time**)
- `prod.exs`, `dev.exs`, and `test.exs` apply for to a specific environment (**compile-time**)
- `dev.secret.exs` is used for local development (**compile-time** ~= **runtime** when running locally via `mix`)
- `runtime.exs` (or previously `releases.exs`) is used when starting up a release (**runtime**)

`System.get_env('ABC')` is used to load system environment variables into those config files, but the difference between runtime and compile-time is _super important_ when using environment variables. If you use environment variables in any of those **compile-time** files, then you might be surprised at what comes out. Everything we deploy gets compiled in a docker build in our CI jobs in travis, meaning the environment variables you get in **compile-time** config come from that build environment. What we really want is to use environment variables provided to your app in the deployment environment, at **runtime**. So it usually only makes sense to use `System.get_env()` in `runtime.exs`.

**Review by ijadams — APPROVED** [review]

**Review by ZachFontenot — COMMENTED** [review]
MERGE IT

**Comment by stuartjohnpage** [comment]
I'm trying to merge this, I think once I merge #1036 this should be good to be merged

**Comment by pjdiiori** [comment]
😅 totally forgot about this. thanks @stuartjohnpage

**Comment by stuartjohnpage** [comment]
No worries! On the other hand...is this based on a fork of the repo??

**Comment by pjdiiori** [comment]
Whoops. Yeah I accidentally forked the repo and pointed it at `main`. closing this. new PR here: #1037

**Pull request closed without merging**
