### PR TITLE
Bump version on elixir and erlang, formatting, rm wp-login.php, java tap name changed

### PR DESCRIPTION
**Pull request by ijadams**
#### Reviewer don't-forgets:

- [ ] Test coverage feels appropriate, given potential risk
- [ ] We're not doubling down on already-bad code
- [ ] If there are web UI changes, they don't add anything that could be considered client-side page navigation (unless pre-approved as being necessary by another engineer)
- [ ] If there are web UI changes, they don't add any AJAX form submits (unless pre-approved as being necessary by another engineer)
- [ ] If there are any lint rules disabled, they are disabled per-line, and were (in the reviewer's judgment) appropriate to disable
- [ ] Any new environment variables used in the app are both documented and have been added to both staging and production environments already
- [ ] Potential race conditions are either inconsequential, or the code prevents them from occurring.
- [ ] If this is a UI change that called for screenshots/GIFs, in the reviewer's judgement, they were included

### CODE REVIEW

**Review by lukeledet — APPROVED** [review]

**Review by lukeledet — CHANGES_REQUESTED** [review]
Noticed that travis is using different versions when running tests, please update .travis.yml with these elixir and erlang versions and make sure node versions match too

**Comment by ijadams** [comment]
Is it a concern that the last commit passes travis but fails `reviewtron-revelry-prod bot`?

**Review by jessrichmond — APPROVED** [review]

**Comment by ijadams** [comment]
`npm test --prefix assets` in the travis build fails when importing es6 export syntax from harmonium's npm package. This is an issue with this line:

`    "test": "TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\", \"esModuleInterop\": true}' NODE_ENV=test nyc --all --reporter=text mocha --require jsdom-global/register --require mocha.setup.js --require ts-node/register test/**/*.[jt]s* test/*.[jt]s*"
`

I couldnt find the right way to either get the right babel compiler or ignore the node_modules harmonium vanilla js import. Didnt feel like converting vanilla.js to module.export syntax so I decided to just nuke the test that is pretty minimal anyways.

**Comment by ijadams** [comment]
> `npm test --prefix assets` in the travis build fails when importing es6 export syntax from harmonium's npm package. I spent a good amount of time messing with this line:
> 
> ` "test": "TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\", \"esModuleInterop\": true}' NODE_ENV=test nyc --all --reporter=text mocha --require jsdom-global/register --require mocha.setup.js --require ts-node/register test/**/*.[jt]s* test/*.[jt]s*"`
> 
> I couldnt find the right way to either get the right babel compiler or ignore the node_modules harmonium vanilla js import. Didnt feel like converting vanilla.js to module.export syntax so I decided to just nuke the test that is pretty minimal anyways.

Added esm and it seems to be working.

**Comment by ijadams** [comment]
@lukeledet can I get a re-review on this?

**Pull request merged**
